Force full backup on specified day in daily schedule
libopenstorage/stork pull request #1148
Opened 2022-08-29 13:01 UTC by ram-infrac

**What type of PR is this?**
>improvement

**What this PR does / why we need it**:
Daily schedule policy now accept `fulbackup` day which will result in force full backup of volume 

**Does this PR change a user-facing CRD or CLI?**:
yes

```
apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumeSnapshotSchedule
metadata:
  name: mysql-snapshot-schedule
  namespace: test
  annotations:
    portworx/snapshot-type: cloud
spec:
  schedulePolicyName: daily
  suspend: false
  reclaimPolicy: Delete
  template:
    spec:
      persistentVolumeClaimName: mysql-data
```

**Is a release note needed?**:
yes

```release-note
User can specify `forceFullSnapshotDay`  in daily snapshot schedule policy to ensure full volume backup on specified day
```

**Does this change need to be cherry-picked to a release branch?**:
yes, 2.12.0

2022-08-29 20:00 UTC, lpitstickpstg commented on pkg/apis/stork/v1alpha1/schedulepolicy.go
> +	// ForceFullSnapshotDay on day specified.
... "specifies day of the week for full snapshot to take place"

2022-08-29 20:06 UTC, lpitstickpstg requested changes
Your example does not contain an example of this being used in spec. We should have a good reference that can also be used in our docs.

Release note should say "... specified day of the week"

2022-08-29 20:06 UTC, lpitstickpstg commented on pkg/schedule/schedule.go
> +	incrementalCountAnnotation = "portworx.io/cloudsnap-incremental-count"
re-definition of constant?

2022-08-30 15:10 UTC, lpitstickpstg approved these changes

2022-08-30 16:32 UTC, adityadani approved these changes

2022-08-30 16:32 UTC, adityadani commented on pkg/schedule/schedule.go
> +			logrus.Debugf("Forcing full-snapshot for daily snapshotschedule policy on the day %s", schedulePolicy.Policy.Daily.ForceFullSnapshotDay)
This can be an info log line. Will be helpful while debugging.

2022-08-30 23:49 UTC, merged