PWX-30276: Do not delete pods running on storage down nodes.
libopenstorage/stork pull request #1385
Opened 2023-04-29 01:10 UTC by adityadani

**What type of PR is this?**
> Uncomment only one and also add the corresponding label in the PR:
>bug

**What this PR does / why we need it**:
- Introduce a new state in Stork for storage down nodes.
- Remap portworx StorageDown state to Stork's StorageDown state
- For degraded node state:
  - filter out the nodes from extender requests.
  - monitor should delete the pods running on them
- For storage down state:
  - do not filter out such nodes.
  - give a low score to nodes which are storage down.
  - monitor should not delete pods running on them

**Does this PR change a user-facing CRD or CLI?**:
No

**Is a release note needed?**:

```release-note
Issue: Stork would delete pods running on Degraded or Portworx StorageDown nodes.
User Impact: Applications would face disruption even though drivers like Portworx supported applications running on StorageDown nodes.
Resolution: Stork will not delete pods running on StorageDown nodes.

```

**Does this change need to be cherry-picked to a release branch?**:
Yes - 23.4

**Testing Notes**
- Added a UT to ensure pods are not deleted on StorageDown nodes.
- Modified existing UTs to use StorageDown state instead of NodeDegraded state. 
- Added a UT in extender to not schedule pods on Degraded nodes.
- Currently working on adding integration tests.

2023-05-01 17:47 UTC, pp511 commented on pkg/monitor/monitor.go
> +				if node.Status == volume.NodeOffline || node.Status == volume.NodeDegraded {
During exponential backoff we check for node condition again here 
https://github.com/libopenstorage/stork/blob/master/pkg/monitor/monitor.go#:~:text=if%20n.Status%20!%3D%20volume.NodeOnline%20%7B
This condition should be updated too.

2023-05-01 18:22 UTC, pp511 commented on pkg/extender/extender_test.go
> +		t.Fatalf("Error setting node status to StorageDown: %v", err)
nit.. StorageDown->NodeDegraded

2023-05-01 18:25 UTC, pp511 commented on pkg/extender/extender_test.go
> +	if err := driver.UpdateNodeStatus(5, volume.NodeDegraded); err != nil {
I think we will need to call CreateCluster(6, nodes) above to simulate a 6 node cluster with 1 node in node degraded state.

2023-05-01 18:25 UTC, pp511 commented on pkg/extender/extender_test.go
> +		t.Fatalf("Error setting node status to StorageDown: %v", err)
nit.. StorageDown->NodeDegraded

2023-05-01 18:27 UTC, pp511 commented on pkg/monitor/monitor_test.go
> +	require.NoError(t, err, "Error setting node status to Degraded")
Nit..Degraded->StorageDown

2023-05-01 18:29 UTC, pp511 requested changes
Overall looks good.
Some nitpicks.
One comment in monitor.go needs to be addressed before we merge.

2023-05-03 21:38 UTC, pp511 commented on pkg/monitor/monitor_test.go
> +	require.NoError(t, err, "Error setting node status to Degraded")
You missed updating this.

2023-05-03 21:55 UTC, pp511 approved these changes
lgtm. just one nit that you missed addressing. ok to merge after CBTs pass.

2023-05-04 01:09 UTC, adityadani commented
Thanks @pp511 ! Will fix the missed comment. Currently trying to get a successful integration test run with the newly added tests. Will merge it once I get a success.

2023-05-08 18:10 UTC, pp511 commented on test/integration_test/extender_test.go
> +	require.NoError(t, err, "Error starting driver on Node %+v", scheduledNodes[0])
nit..Error exiting pool maintenance

2023-05-08 18:10 UTC, pp511 commented on test/integration_test/extender_test.go
> +	require.NoError(t, err, "Error stopping driver on scheduled Node %+v", scheduledNodes[0])
Nit..Error stopping driver -> Error entering pool maintenance

2023-05-08 18:12 UTC, pp511 commented
Integration tests look good. Just two nits that need to be addressed

2023-05-09 16:02 UTC, merged